MVCCore_DM1_StarterKit/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using MVCCoreStarterKit.Attributes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace MVCCoreStarterKit.Controllers
{
    public class DashboardController : Controller
    {
        #region Methods
        /// <summary>
        /// Action for rendering a dashboard viewer.
        /// </summary>
        /// <param name="id">The dashboard ID</param>
        /// <returns>DashboardViewer View</returns>
        [Theme]
        public IActionResult DashboardViewer(string id)
        {
            var query = Request.Query;
            dynamic filters = new System.Dynamic.ExpandoObject();
            foreach (string key in query.Keys)
            {
                ((IDictionary<string, Object>)filters).Add(key, query[key]);
            }

            ViewBag.Id = id;
            ViewBag.filters = JsonConvert.SerializeObject(filters);
            return View();
        } 
        #endregion
    }
}

MVCCore_DM1_StarterKit/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using MVCCoreStarterKit.Attributes;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace MVCCoreStarterKit.Controllers
{
    public class ReportController : Controller
    {
        #region Methods
        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Action for rendering report viewer.
        /// </summary>
        /// <param name="id">Report id used for rendering</param>
        /// <returns>ReportViewer View</returns>
        [Theme]
        public ActionResult ReportViewer(string id)
        {
            var query = Request.Query;
            dynamic filters = new System.Dynamic.ExpandoObject();
            foreach (string key in query.Keys)
            {
                ((IDictionary<string, Object>)filters).Add(key, query[key]);
            }

            ViewBag.overridingFilterQueries = JsonConvert.SerializeObject(filters); ;
            ViewBag.Id = id;
            return View();
        }

        /// <summary>
        /// Action for rendering page with multiple report parts.
        /// </summary>
        /// <returns>ReportParts View</returns>
        [Theme]
        public ActionResult ReportParts()
        {
            return View();
        } 
        #endregion
    }
}

MVCCore_DM1_StarterKit/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Identity
@using MVCCoreStarterKit.Areas.Identity.Model
@inject SignInManager<IzendaUser> SignInManager
<li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link text-dark" })</li>
@if (SignInManager.IsSignedIn(User))
{
    <li>@Html.ActionLink("Izenda", "Izenda", "Home", null, new { @class = "nav-link text-dark" })</li>
    <li>@Html.ActionLink("Settings", "Settings", "Home", null, new { @class = "nav-link text-dark" })</li>
    @*<li>@Html.ActionLink("Mixed Parts", "MixedParts", "Home", null, new { @class = "nav-link text-dark" })</li>*@

    @* Reports *@
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#">
            Reports
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("New Report", "ReportDesigner", "Home", null, new { @class = "nav-link text-dark" })</li>
            <li>@Html.ActionLink("Report List", "Reports", "Home", null, new { @class = "nav-link text-dark" })</li>
            @* Add to report Viewer to Demo, hardcode Report ID to link user to a specific report - please update the report id with one created in your enviroment*@
            <li>@Html.ActionLink("Report Viewer", "ReportViewer", "Report", new { id = "[your report id]" }, new { @class = "nav-link text-dark" })</li>
            <li>@Html.ActionLink("Report Parts", "ReportParts", "Report", null, new { @class = "nav-link text-dark" })</li>
        </ul>
    </li>

    @* Dashboards *@
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#">
            Dashboards
            <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li>@Html.ActionLink("New Dashboard", "DashboardDesigner", "Home", null, new { @class = "nav-link text-dark" })</li>
            <li>@Html.ActionLink("Dashboard List", "Dashboards", "Home", null, new { @class = "nav-link text-dark" })</li>
            @* Add to report Viewer to Demo, hardcode Report ID to link user to a specific report - please update the report id with one created in your enviroment*@
            <li>@Html.ActionLink("Dashboard Viewer", "DashboardViewer", "Dashboard", new { id = "[your dashboard id]" }, new { @class = "nav-link text-dark" })</li>
        </ul>
    </li>
}

MVCCore_DM1_StarterKit/Views/Shared/_IzendaLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCoreStarterKit</title>

    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />

    @* Apply css based on the users tenant *@
    <link href="~/js/izenda/izenda-ui.css" rel="stylesheet" />
    <link href="~/css/izenda_visualizations.css" rel="stylesheet" />

    @*Add Custom CSS based on the tenantId and path set in izendaCssPath above *@
    <link href=@ViewBag.izendaCssPath rel="stylesheet">
</head>
<body>

    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <script src="~/js/jquery-1.10.2.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/alertify.js"></script>
    <script src="~/js/izenda/izenda_common.js"></script>
    <script src="~/js/izenda/izenda_locales.js"></script>
    <script src="~/js/izenda/izenda_vendors.js"></script>
    <script src="~/js/izenda/izenda_ui.js"></script>
    <script src="~/js/izenda.integrate.js"></script>
    <script src="~/js/izenda.utils.js"></script>
    <script src="~/js/izenda_visualizations.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            DoIzendaConfig();
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="dropdown"]').dropdown();
            $("#reportPartLoader").hide();
            $("#reportPartLoaderText").hide();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MVCCore_DM1_StarterKit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCCoreStarterKit</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/izenda_visualizations.css" rel="stylesheet" />
    @* Apply css based on the users tenant *@
    <link href="~/js/izenda/izenda-ui.css" rel="stylesheet" />

    @*Add Custom CSS based on the tenantId and path set in izendaCssPath above *@
    <link href=@ViewBag.izendaCssPath rel="stylesheet">
</head>
<body>

    <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="navbar-header pull-left">
                        <a class="navbar-brand" href="https://www.izenda.com/" target="_blank" rel="noopener noreferrer">
                            <img src="https://3u8npt2xyr3u2fgvai49zopv-wpengine.netdna-ssl.com/wp-content/uploads/2019/05/izenda-logo-white.png"
                                 alt="Site Logo" style="height:18px; width: 100px" />
                        </a>
                    </div>
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("MVC Core StarterKit", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="nav navbar-nav">
                        <partial name="_Header" />
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </header>
    <div class="container-fluid body-content">
        @RenderBody()
    </div>
    <div style="bottom:0;position: fixed; width:100%;">
        <footer>
            <p>&copy; @DateTime.Now.Year - Izenda Integrated BI Platform</p>
        </footer>
    </div>

    <script rel="preload" src="~/js/jquery-1.10.2.min.js"></script>
    <script rel="preload" src="~/js/bootstrap.min.js"></script>
    <script rel="preload" src="~/js/site.js" asp-append-version="true"></script>
    <script rel="preload" src="~/js/alertify.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_common.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_locales.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_vendors.js"></script>
    <script rel="prefetch" src="~/js/izenda/izenda_ui.js"></script>
    <script rel="prefetch" src="~/js/izenda.integrate.js"></script>
    <script rel="prefetch" src="~/js/izenda.utils.js"></script>
    <script rel="prefetch" src="~/js/izenda_visualizations.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            DoIzendaConfig();
            $('[data-toggle="tooltip"]').tooltip();
            $('[data-toggle="dropdown"]').dropdown();
            $("#reportPartLoader").hide();
            $("#reportPartLoaderText").hide();
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>